#!/bin/bash

usage() {
    echo "usage: $0 -i=<path to iswinfo directory> -o=<path store output files>"
}

while getopts "i:o:" options; do
    case $options in
        i ) input=$OPTARG;;
        o ) output=$OPTARG;;
        h ) usage;;
        * ) usage
            exit 1;;
    esac
done

if [ -z "$input" ] || [ -z "$output"]; then
   usage
   exit 1
fi

script_dir=$(dirname "$0")

python "${script_dir}/isw/iswgen.py" -i "$input" -o "${output}/generated"
mkdir -p "${output}/qts"
"${script_dir}/qts-filter.sh" "cyclone5" "${input}/../../" "$output" "${output}/qts"
