/* GENERATED FILE - DO NOT EDIT */
/*
 * Copyright Altera Corporation (C) 2012-2014. All rights reserved
 *
 * SPDX-License-Identifier:    BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    * Neither the name of Altera Corporation nor the
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ALTERA CORPORATION BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PRELOADER_RESET_CONFIG_H_
#define _PRELOADER_RESET_CONFIG_H_

/* 1 mean that particular IP need to be kept under reset state */
#define CONFIG_HPS_RESET_ASSERT_EMAC0		(${DERIVED_RESET_ASSERT_RGMII0})
#define CONFIG_HPS_RESET_ASSERT_EMAC1		(${DERIVED_RESET_ASSERT_RGMII1})
#define CONFIG_HPS_RESET_ASSERT_USB0		(${DERIVED_RESET_ASSERT_USB0})
#define CONFIG_HPS_RESET_ASSERT_USB1		(${DERIVED_RESET_ASSERT_USB1})
#define CONFIG_HPS_RESET_ASSERT_NAND		(${DERIVED_RESET_ASSERT_NAND})
#define CONFIG_HPS_RESET_ASSERT_SDMMC		(${DERIVED_RESET_ASSERT_SDMMC})
#define CONFIG_HPS_RESET_ASSERT_QSPI		(${DERIVED_RESET_ASSERT_QSPI})
#define CONFIG_HPS_RESET_ASSERT_UART0		(${DERIVED_RESET_ASSERT_UART0})
#define CONFIG_HPS_RESET_ASSERT_UART1		(${DERIVED_RESET_ASSERT_UART1})
#define CONFIG_HPS_RESET_ASSERT_I2C0		(${DERIVED_RESET_ASSERT_I2C0})
#define CONFIG_HPS_RESET_ASSERT_I2C1		(${DERIVED_RESET_ASSERT_I2C1})
#define CONFIG_HPS_RESET_ASSERT_I2C2		(${DERIVED_RESET_ASSERT_I2C2})
#define CONFIG_HPS_RESET_ASSERT_I2C3		(${DERIVED_RESET_ASSERT_I2C3})
#define CONFIG_HPS_RESET_ASSERT_SPIM0		(${DERIVED_RESET_ASSERT_SPIM0})
#define CONFIG_HPS_RESET_ASSERT_SPIM1		(${DERIVED_RESET_ASSERT_SPIM1})
#define CONFIG_HPS_RESET_ASSERT_SPIS0		(${DERIVED_RESET_ASSERT_SPIS0})
#define CONFIG_HPS_RESET_ASSERT_SPIS1		(${DERIVED_RESET_ASSERT_SPIS1})
#define CONFIG_HPS_RESET_ASSERT_CAN0		(${DERIVED_RESET_ASSERT_CAN0})
#define CONFIG_HPS_RESET_ASSERT_CAN1		(${DERIVED_RESET_ASSERT_CAN1})
#define CONFIG_HPS_RESET_ASSERT_L4WD1		(${spl.reset_assert.L4WD1})
#define CONFIG_HPS_RESET_ASSERT_OSC1TIMER1	(${spl.reset_assert.OSC1TIMER1})
#define CONFIG_HPS_RESET_ASSERT_SPTIMER0	(${spl.reset_assert.SPTIMER0})
#define CONFIG_HPS_RESET_ASSERT_SPTIMER1	(${spl.reset_assert.SPTIMER1})
#define CONFIG_HPS_RESET_ASSERT_GPIO0		(${spl.reset_assert.GPIO0})
#define CONFIG_HPS_RESET_ASSERT_GPIO1		(${spl.reset_assert.GPIO1})
#define CONFIG_HPS_RESET_ASSERT_GPIO2		(${spl.reset_assert.GPIO2})
#define CONFIG_HPS_RESET_ASSERT_DMA		(${spl.reset_assert.DMA})
#define CONFIG_HPS_RESET_ASSERT_SDR		(${spl.reset_assert.SDR})

#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA0	(${DERIVED_RESET_ASSERT_FPGA_DMA0})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA1	(${DERIVED_RESET_ASSERT_FPGA_DMA1})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA2	(${DERIVED_RESET_ASSERT_FPGA_DMA2})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA3	(${DERIVED_RESET_ASSERT_FPGA_DMA3})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA4	(${DERIVED_RESET_ASSERT_FPGA_DMA4})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA5	(${DERIVED_RESET_ASSERT_FPGA_DMA5})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA6	(${DERIVED_RESET_ASSERT_FPGA_DMA6})
#define CONFIG_HPS_RESET_ASSERT_FPGA_DMA7	(${DERIVED_RESET_ASSERT_FPGA_DMA7})

#define CONFIG_HPS_RESET_ASSERT_HPS2FPGA	(${DERIVED_RESET_ASSERT_HPS2FPGA})
#define CONFIG_HPS_RESET_ASSERT_LWHPS2FPGA	(${DERIVED_RESET_ASSERT_LWHPS2FPGA})
#define CONFIG_HPS_RESET_ASSERT_FPGA2HPS	(${DERIVED_RESET_ASSERT_FPGA2HPS})

#define CONFIG_HPS_RESET_WARMRST_HANDSHAKE_FPGA		(${spl.warm_reset_handshake.FPGA})
#define CONFIG_HPS_RESET_WARMRST_HANDSHAKE_ETR		(${spl.warm_reset_handshake.ETR})
#define CONFIG_HPS_RESET_WARMRST_HANDSHAKE_SDRAM	(${spl.warm_reset_handshake.SDRAM})

#endif /* _PRELOADER_RESET_CONFIG_H_ */
